      SubroutineTranEq
      IMPLICITREAL*8(A-H,O-Z)
      PARAMETER(NVARS=3)
      PARAMETER(NFREQ=96+4)
      PARAMETER(Mzon=500)
      PARAMETER(NYDIM=(NVARS+2*NFREQ)*Mzon,MAXDER=4)
      Parameter(Is=5)
      PARAMETER(NZ=3000000)
      Parameter(Nstage=28,Natom=15)
      PARAMETER(KOMAX=80)
      LogicalLSYSTEM
      Parameter(LSystem=.FALSE.)
      Parameter(Pi=3.1415926535897932d+00,hPlanc=1.0545716280D-27,Cs=2.9
     *979245800D+10,Boltzk=1.3806504000D-16,Avogar=6.0221417900D+23,AMbr
     *un=1.6605387832D-24,AMelec=9.1093821500D-28,echarg=4.8032042700D-1
     *0,CG=6.6742800000D-08,CMS=1.9884000000D+33,RSol=6.9551000000D+10,U
     *LGR=1.4000000000D+01,UPURS=1.0000000000D+07,ULGPU=7.0000000000D+00
     *,ULGEU=1.3000000000D+01,UPC=3.0856776000D+18,UTP=1.0000000000D+05,
     *URHO=1.0000000000D-06,CARAD=7.5657680191D-15,CSIGM=5.6704004778D-0
     *5,ERGEV=1.6021764864D-12,GRADeV=1.1604505285D+04,RADC=7.5657680191
     *D-02,CTOMP=4.0062048575D-01,CCAPS=2.6901213726D+01,CCAPZ=9.8964034
     *725D+00)
      IntegerZn(Natom),ZnCo(Natom+1)
      DimensionAZ(Natom)
      Common/AZZn/AZ,Zn,ZnCo
      Common/NiAdap/tday,t_eve,XNifor(Mzon),AMeveNi,KNadap
      LOGICALFRST
      Parameter(Mfreq=130)
      Common/Kmzon/km,kmhap,Jac,FRST
      COMMON/STCOM1/t,H,HMIN,HMAX,EPS,N,METH,KFLAG,JSTART
      COMMON/YMAX/YMAX(NYDIM)
      COMMON/YSTIF/Y(NYDIM,MAXDER+1)
      COMMON/HNUSED/HUSED,NQUSED,NFUN,NJAC,NITER,NFAIL
      COMMON/HNT/HNT(7)
      PARAMETER(DELTA=1.d-05)
      PARAMETER(LICN=4*NZ,LIRN=2*NZ)
      LogicalNEEDBR
      COMMON/STJAC/THRMAT,HL,AJAC(LICN),IRN(LIRN),ICN(LICN),WJAC(NYDIM),
     *FSAVE(NYDIM*2),IKEEP(5*NYDIM),IW(8*NYDIM),IDISP(11),NZMOD,NEEDBR
      LOGICALCONV,CHNCND,SCAT,SEP
      COMMON/CUTOFF/FLOOR(NVARS+1),Wacc(NVARS+1),FitTau,TauTol,Rvis,CONV
     *,CHNCND,SCAT,SEP
      LogicalLTHICK
      COMMON/THICK/LTHICK(Nfreq,Mzon)
      COMMON/CONVEC/UC(Mzon),YAINV(Mzon)
      COMMON/RAD/EDDJ(Mzon,Nfreq),EDDH(Mzon),HEDD(Nfreq),HEDRAD,CLIGHT,C
     *KRAD,UFREQ,CFLUX,CCL,CLUM,CLUMF,CIMP,NTHICK(NFREQ),NTHNEW(NFREQ),N
     *CND,KRAD,NFRUS
      LOGICALEDTM
      COMMON/RADOLD/HEDOLD,HINEDD,EDTM
      Common/newedd/EddN(Mzon,Nfreq),HEdN(Nfreq),tfeau
      Common/oldedd/EddO(Mzon,Nfreq),HEdo(Nfreq),trlx
      Common/cnlast/Cnlast
      Common/Dhap/DHaphR(Mzon,Nfreq)
      COMMON/BAND/FREQ(NFREQ+1),FREQMN(NFREQ),WEIGHT(130),HAPPAL(NFREQ),
     *HAPABSRON(NFREQ),HAPABS(NFREQ),DLOGNU(NFREQ)
      PARAMETER(NFRMIN=Nfreq/2)
      IntegerdLfrMax
      Common/observer/wH(Mfreq),cH(Mfreq),zerfr,Hcom(Mfreq),Hobs(Mfreq),
     *freqob(Mfreq),dLfrMax
      Parameter(NP=15+15-1)
      Common/famu/fstatic(0:NP+1,Nfreq),fobs_corr(0:NP+1,Mfreq),fcom(0:N
     *P+1,Mfreq),amustatic(0:NP+1)
      Common/rays/Pray(0:Np+1),fout(0:NP+1,Mfreq),abermu(0:NP+1),NmuNzon
      COMMON/LIM/Uplim,Haplim
      COMMON/AMM/DMIN,DM(Mzon),DMOUT,AMINI,AM(Mzon),AMOUT
      COMMON/Centr/RCE,Nzon
      Common/InEn/AMHT,EBurst,tBurst,tbeght
      COMMON/RADPUM/AMNI,XMNi,XNi,KmNick
      COMMON/RADGAM/FJgam(Mzon,2),toldg,tnewg
      COMMON/RADGlg/FJglog(Mzon,2)
      COMMON/CHEM/CHEM0(Mzon),RTphi(0:Mzon+1),EpsUq
      COMMON/REGIME/NREG(Mzon)
      doubleprecisionNRT
      COMMON/AQ/AQ,BQ,DRT,NRT
      COMMON/AZNUC/ACARB,ZCARB,ASI,ZSI,ANI,ZNI,QCSI,QSINI
      COMMON/QNRGYE/QNUC,RGASA,YELECT
      COMMON/CKN1/CK1,CK2,CFR,CRAP,CRAOLD
      LOGICALEVALJA,OLDJAC,BADSTE
      COMMON/EVAL/EVALJA,BADSTE,OLDJAC
      LogicalRadP
      COMMON/RadP/RadP
      COMMON/ARG/TP,PL,CHEM,LST,KENTR,JURS
      COMMON/RESULT/P,Egas,Sgas,ENG,CAPPA,PT,ET,ST,ENGT,CAPT,NZR
      COMMON/ABUND/XYZA,Yat(Natom)
      COMMON/AZ/AS,ZS,SCN
      COMMON/STR/PPL,EPL,SPL,ENGPL,CAPPL,CP,GAM,DA,DPE,DSE,DSP,BETgas
      COMMON/XELECT/XE,XET,XEPL,PE,Ycomp
      COMMON/URScap/Tpsqrt,Psicap,Scap,ScapT,ScapPl,ZMean,YZMean,ZMT,ZMP
     *l,YZMT,YZMPl
      COMMON/BURNCC/CC,CCTP,CCPL,YDOT
      COMMON/ABarr/YABUN(Natom,Mzon)
      COMMON/UNSTL/UL,UPRESS,UE,UEPS,UCAP,UTIME,UV,UFLUX,UP
      COMMON/TAIL/KTAIL
      COMMON/UNINV/UPI,UEI
      COMMON/UNBSTL/UR,UM,UEPRI,ULGP,ULGE,ULGV,ULGTM,ULGEST,ULGFL,ULGCAP
     *,ULGEPS
      common/NSTEP/NSTEP,NDebug,MAXER,IOUT,NOUT
      common/CREAD/TAUOLD,NSTMAX,MBATCH,MAXORD
      common/debug/LfrDebug,Nperturb,Kbad
      PARAMETER(ALFCON=1.D0)
      Common/Hydro/dm0,dm1,dm2,Rodm,RSodm,R0,R1,R2,RSm1,RS0,RS1,RS2,RC0,
     *RC1,RC2,Rcinv0,RCinv1,RCinv2,U0,U1,U2,Q1,Q2,QU1,QU2,UDIVR,UU1,UU2,
     *UQ1,UQ2,AQ1,AQ2,QUHALF
      Common/Termo/PL0,PL1,PL2,ET1,ET2,Tp0,Tp1,Tp2,PQ1,PQ2,PQpl1,PQpl2,P
     *T1,PT2,TPTQ1,TPTQ2,TpT1,TpT2,Tp0up4,Tp1up4,Tp2up4,PTPL1,PTPL2,PTT1
     *,PTT2,ETPL1,ETPL2,ETT1,ETT2,DMETIN,CDMETI,CK2ET1,HEATRA,FLUM,FIMP,
     *DTPOLD,ENG0,ENG1,ENG2,ENGPL1,ENGPL2,ENGT1,ENGT2
      Common/Tratst/TOTJ,TOTW,TOTWPR
      Common/Convo/PP0,PP1,PP2,CP0,CP1,CP2,GRA0,GRA1,GRA2,VCSQ0,VCSQ1,FC
     *0,FC1,ELMIX0,ELMIX1,CFC0,CFC1,CPPL0,CPPL1,CPPL2,CPT0,CPT1,CPT2,GRA
     *PL0,GRAPL1,GRAPL2,GRAT0,GRAT1,GRAT2,PRPL0,PRPL1,PRPL2,PRT0,PRT1,PR
     *T2
      Common/Fluxo/tau1(Nfreq),tau2(Nfreq),FL0,FL1,Flcor1,Flcor2,Fllf0,F
     *lrt0,Fllf1,Flrt1,FLcore,CAPcor,CAP0,CAP1,CAP2,CAP1D,CAP1T,CAPT0,CA
     *PT1,CAPT2,CAPPL0,CAPPL1,CAPPL2,CM0INV,CM1INV
      Common/Transo/DJNU(NFREQ),B24(NFREQ),DFH(NFREQ),DFJ(NFREQ),DUR(NFR
     *EQ),DFJDPL(NFREQ),DFHDPL(NFREQ),HAPL(NFREQ),HAPL1(NFREQ),HAPL2(NFR
     *EQ),HAPL1T(NFREQ),HAPL2T(NFREQ),HAPL1D(NFREQ),HAPL2D(NFREQ),HAPH(N
     *FREQ),HAPH1(NFREQ),HAAB(NFREQ),HAAB1(NFREQ),HAAB2(NFREQ),HAAB1T(NF
     *REQ),HAAB2T(NFREQ),HAAB1D(NFREQ),HAAB2D(NFREQ),FHcore(NFREQ),BLCKD
     *(NFREQ)
      Common/Burno/YDOT1,YDOT2,CCPL1,CCPL2,CCTP1,CCTP2,AS1,AS2,YCARB1,YC
     *ARB2
      BLACK(Lbl,Tpbl)=(exp(-(FREQMN(Lbl)/Tpbl)))/(1.d0-(exp(-(FREQMN(Lbl
     *)/Tpbl))))
      BLACKD(Lbl,Tpbl)=(FREQMN(Lbl)/Tpbl)*(exp(-(FREQMN(Lbl)/Tpbl)))/(1.
     *d0-(exp(-(FREQMN(Lbl)/Tpbl))))**2
      TOTJ=0.D0
      TOTJPR=0.D0
      TOTW=0.D0
      TOTWPR=0.D0
      IF(Km==Ncnd+1)THEN
      DO09999L=1,NFRUS
      BLCKD(L)=BLACKD(L,(0.5D0*(Tp+Tp0)))
09999 CONTINUE
      ENDIF
      DO09996L=1,NFRUS
      IF(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*WEIGHT(L)<-1.D0.AND
     *.FRST)THEN
      BADSTE=.TRUE.
      WRITE(*,'('' NSTEP Km L FJ(B C) FH(B) '',3I5,1P,3E10.2)')NSTEP,Km,
     *L,FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km),FSAVE(NVARS*NZON-Ncn
     *d+(NZON-Ncnd)*(L-1)+Km+1),FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(
     *L-1)+Km)
      RETURN
      ENDIF
      IF(FRST)THEN
      IF(DUR(L)>0.D0)THEN
      IF(.NOT.(L==1))GOTO09993
      DJNU(1)=FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*L+Km)*DUR(2)*FREQMN(2)**
     *4/WEIGHT(1)
      GOTO09991
09993 CONTINUE
      IF(.NOT.(L==NFRUS))GOTO09992
      DJNU(L)=-FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*DUR(L)*FREQMN
     *(L)**4/WEIGHT(L)
      GOTO09991
09992 CONTINUE
      DJNU(L)=(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*L+Km)*DUR(L+1)*FREQMN(L
     *+1)**4-FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*DUR(L)*FREQMN(L
     *)**4)/WEIGHT(L)
09991 CONTINUE
      ELSE
      IF(.NOT.(L==1))GOTO09990
      DJNU(1)=FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*DUR(1)*FREQMN(
     *1)**4/WEIGHT(1)
      GOTO09988
09990 CONTINUE
      IF(.NOT.(L==NFRUS))GOTO09989
      DJNU(L)=-FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-2)+Km)*DUR(L-1)*FREQ
     *MN(L-1)**4/WEIGHT(L)
      GOTO09988
09989 CONTINUE
      DJNU(L)=(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*DUR(L)*FREQMN
     *(L)**4-FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-2)+Km)*DUR(L-1)*FREQMN
     *(L-1)**4)/WEIGHT(L)
09988 CONTINUE
      ENDIF
      ENDIF
      IF(Km==Ncnd+1)THEN
      IF(Km>1)THEN
      FH0=FLcore*BLCKD(L)*CAPcor/(6.D0*(0.5D0*(Tp+Tp0))**4*RS0*HAPL(L))
      ELSE
      FH0=FLcore
      ENDIF
      IF(FRST)FHcore(L)=FH0
      ELSE
      IF(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km-1))>FLOOR(N
     *VARS+1).AND.Ncnd<0)THEN
      IF(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km-1)<0.D0)THEN
      FH0=-MIN(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km-1)),A
     *BS(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km))*2.0D0*EDDH(KM))
      ELSE
      FH0=MIN(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km-1)),AB
     *S(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km-1))*2.0D0*EDDH(KM))
      ENDIF
      ELSE
      FH0=FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km-1)
      ENDIF
      ENDIF
      IF(Km<NZON)THEN
      IF(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km))>FLOOR(NVA
     *RS+1).AND.Ncnd<0)THEN
      IF(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)<0.D0)THEN
      FH1=-MIN(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)),ABS
     *(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km+1))*2.0D0*EDDH(KM))
      ELSE
      FH1=MIN(ABS(FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)),ABS(
     *FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km))*2.0D0*EDDH(KM))
      ENDIF
      ELSE
      FH1=FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)
      ENDIF
      ELSE
      FH1=HEDD(L)*FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)
      ENDIF
      DFJ(L)=-FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*((U1-U0)/(R1-R
     *0)*(1.D0+EDDJ(Km,L))+(3.D0-EDDJ(Km,L))*UDIVR)+DJNU(L)+CLIGHT*(-(FH
     *1*RS1-FH0*RS0)*RCinv1+HAAB(L)*PL*(BLACK(L,Tp)-FSAVE(NVARS*NZON-Ncn
     *d+(NZON-Ncnd)*(L-1)+Km)))
      IF(Km<NZON)THEN
      DFH(L)=-4.D0*FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)*U1/R
     *1+CLIGHT*(-(EDDJ(Km+1,L)*FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+K
     *m+1)-EDDJ(Km,L)*FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km))*2.D0/
     *(R2-R0)-HAPH(L)*3.D0*(DM1+DM2)/(RC2-RC0)*FSAVE(NVARS*NZON-Ncnd+KRA
     *D+(NZON-Ncnd)*(L-1)+Km)-((1.5D0*EDDJ(Km,L)-0.5D0)*FSAVE(NVARS*NZON
     *-Ncnd+(NZON-Ncnd)*(L-1)+Km)*R0+(1.5D0*EDDJ(Km+1,L)-0.5D0)*FSAVE(NV
     *ARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km+1)*R2)/RS1)
      If(Nstep>=NDebug.and.Km>Ncnd.and.Km<Ncnd+3.and.L==LfrDebug)then
      write(4,'(3(A,I10))')' LfrDebug=',LfrDebug,' Nperturb=',Nperturb
      write(4,*)' traneq Km & L DFH(L)=',km,L,DFH(L)
      write(4,'(a,1p,e12.3)')' -4.D0*@FH1*U1/R1=',-4.D0*FSAVE(NVARS*NZON
     *-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km)*U1/R1
      write(4,'(a,1p,e22.12)')' FJ=',CLIGHT*((EDDJ(Km+1,L)*FSAVE(NVARS*N
     *ZON-Ncnd+(NZON-Ncnd)*(L-1)+Km+1)-EDDJ(Km,L)*FSAVE(NVARS*NZON-Ncnd+
     *(NZON-Ncnd)*(L-1)+Km))*2.D0/(R2-R0))
      write(4,'(a,1p,e22.12)')' Haph=',CLIGHT*(-HAPH(L)*3.D0*(DM1+DM2)/(
     *RC2-RC0)*FSAVE(NVARS*NZON-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km))
      write(4,'(a,1p,e12.3)')' EddjFj=',Clight*((1.5D0*EDDJ(Km,L)-0.5D0)
     **FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)/RS1-((1.5D0*EDDJ(Km,L
     *)-0.5D0)*FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*R0+(1.5D0*EDD
     *J(Km+1,L)-0.5D0)*FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km+1)*R2)
     */RS1)
      write(4,*)' Nthick=',Nthick(L)
      endif
      IF(Km/=NZON-1.AND.Km/=Ncnd+1)THEN
      DFH(L)=DFH(L)+CLIGHT*RVIS*(FH0*(RS0/RS1)-2.D0*FH1+FSAVE(NVARS*NZON
     *-Ncnd+KRAD+(NZON-Ncnd)*(L-1)+Km+1)*(RS2/RS1))/(2.D0*(R1-R0))
      If(Nstep>=NDebug.and.Km>Ncnd.and.Km<Ncnd+3.and.L==LfrDebug)then
      write(4,*)' traneq after Rvis DFH(L)=',DFH(L)
      endif
      ELSEIF(Km==NZON-1)THEN
      DFH(L)=DFH(L)+CLIGHT*RVIS*(FH0*(RS0/RS1)-2.D0*FH1+HEDD(L)*FSAVE(NV
     *ARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km+1)*(RS2/RS1))/(2.D0*(R1-R0))
      ENDIF
      ELSE
      DFH(L)=0.D0
      ENDIF
      If(LTHICK(L,Km))Then
      TOTJ=TOTJ-(FH1*RS1-FH0*RS0)/DM1*WEIGHT(L)
      ELSE
      TOTJ=TOTJ+(max(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km),0.D0)-B
     *LACK(L,Tp))*HAAB(L)*WEIGHT(L)
      ENDIF
      TOTJPR=TOTJPR+FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)*WEIGHT(L
     *)
      TOTW=TOTW+(FSAVE(NVARS*NZON-Ncnd+(NZON-Ncnd)*(L-1)+Km)-BLACK(L,Tp)
     *)*HAAB(L)*WEIGHT(L)
      TOTWPR=TOTWPR-(FH1*RS1-FH0*RS0)/DM1*WEIGHT(L)
      If(Nstep>=NDebug.and.Km>Ncnd.and.Km<Ncnd+3.and.L==LfrDebug)then
      write(4,*)' traneq exit Km & L DFH(L)=',DFH(L)
      endif
09996 CONTINUE
      HEATRA=TOTJ*CKRAD
      return
      end
